import type { IconType } from "react-icons";
import {
  HiOutlineArrowLeft,
  HiOutlineArrowPath,
  HiOutlineArrowRight,
  HiBars3,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineChevronUpDown,
  HiOutlineClock,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineMagnifyingGlass,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlineShoppingBag,
  HiOutlineUser,
  HiOutlineXCircle,
  HiOutlineXMark,
} from "react-icons/hi2";
import {
  HiOutlineArrowLeft as Hi1ArrowLeft,
  HiOutlineArrowRight as Hi1ArrowRight,
  HiOutlineRefresh as Hi1ArrowPath,
  HiOutlineMenu as Hi1Menu,
  HiOutlineCheck as Hi1Check,
  HiOutlineCheckCircle as Hi1CheckCircle,
  HiOutlineChevronDown as Hi1ChevronDown,
  HiOutlineChevronLeft as Hi1ChevronLeft,
  HiOutlineChevronRight as Hi1ChevronRight,
  HiOutlineChevronUp as Hi1ChevronUp,
  HiOutlineSelector as Hi1ChevronsUpDown,
  HiOutlineClock as Hi1Clock,
  HiOutlineHeart as Hi1Heart,
  HiOutlineHome as Hi1Home,
  HiOutlineSearch as Hi1Search,
  HiOutlineMinus as Hi1Minus,
  HiOutlinePlus as Hi1Plus,
  HiOutlineShoppingBag as Hi1Cart,
  HiOutlineUser as Hi1User,
  HiOutlineXCircle as Hi1XCircle,
  HiOutlineX as Hi1X,
} from "react-icons/hi";
import {
  LuArrowLeft,
  LuArrowRight,
  LuRefreshCw,
  LuMenu,
  LuCheck,
  LuCircleCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuChevronsUpDown,
  LuClock,
  LuHeart,
  LuHouse,
  LuSearch,
  LuMinus,
  LuPlus,
  LuShoppingBag,
  LuUser,
  LuCircleX,
  LuX,
} from "react-icons/lu";
import {
  MdArrowBack,
  MdArrowForward,
  MdRefresh,
  MdMenu,
  MdCheck,
  MdCheckCircleOutline,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdUnfoldMore,
  MdOutlineAccessTime,
  MdFavoriteBorder,
  MdOutlineHome,
  MdOutlineSearch,
  MdRemove,
  MdAdd,
  MdOutlineShoppingBag,
  MdOutlinePersonOutline,
  MdOutlineCancel,
  MdClose,
} from "react-icons/md";
import {
  FiArrowLeft,
  FiArrowRight,
  FiRefreshCw,
  FiMenu,
  FiCheck,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsUp,
  FiClock,
  FiHeart,
  FiHome,
  FiSearch,
  FiMinus,
  FiPlus,
  FiShoppingBag,
  FiUser,
  FiXCircle,
  FiX,
} from "react-icons/fi";
import {
  BiArrowBack,
  BiRightArrowAlt,
  BiRefresh,
  BiMenu,
  BiCheck,
  BiCheckCircle,
  BiChevronDown,
  BiChevronLeft,
  BiChevronRight,
  BiChevronUp,
  BiExpandVertical,
  BiTime,
  BiHeart,
  BiHome,
  BiSearch,
  BiMinus,
  BiPlus,
  BiShoppingBag,
  BiUser,
  BiXCircle,
  BiX,
} from "react-icons/bi";
import {
  BsArrowLeft,
  BsArrowRight,
  BsArrowRepeat,
  BsList,
  BsCheck,
  BsCheckCircle,
  BsChevronDown,
  BsChevronLeft,
  BsChevronRight,
  BsChevronUp,
  BsChevronExpand,
  BsClock,
  BsHeart,
  BsHouse,
  BsSearch,
  BsDash,
  BsPlus,
  BsCart3,
  BsPerson,
  BsXCircle,
  BsX,
} from "react-icons/bs";
import {
  RxArrowLeft,
  RxArrowRight,
  RxReload,
  RxHamburgerMenu,
  RxCheck,
  RxCheckCircled,
  RxChevronDown,
  RxChevronLeft,
  RxChevronRight,
  RxChevronUp,
  RxCaretSort,
  RxClock,
  RxHeart,
  RxHome,
  RxMagnifyingGlass,
  RxMinus,
  RxPlus,
  RxCube,
  RxPerson,
  RxCrossCircled,
  RxCross2,
} from "react-icons/rx";
import {
  TbArrowLeft,
  TbArrowRight,
  TbRefresh,
  TbMenu2,
  TbCheck,
  TbCircleCheck,
  TbChevronDown,
  TbChevronLeft,
  TbChevronRight,
  TbChevronUp,
  TbSelector,
  TbClock,
  TbHeart,
  TbHome,
  TbSearch,
  TbMinus,
  TbPlus,
  TbShoppingBag,
  TbUser,
  TbCircleX,
  TbX,
} from "react-icons/tb";
import {
  PiArrowLeft,
  PiArrowRight,
  PiArrowsClockwise,
  PiList,
  PiCheck,
  PiCheckCircle,
  PiCaretDown,
  PiCaretLeft,
  PiCaretRight,
  PiCaretUp,
  PiCaretUpDown,
  PiClock,
  PiHeart,
  PiHouse,
  PiMagnifyingGlass,
  PiMinus,
  PiPlus,
  PiShoppingBag,
  PiUser,
  PiXCircle,
  PiX,
} from "react-icons/pi";
import {
  RiArrowLeftLine,
  RiArrowRightLine,
  RiRefreshLine,
  RiMenuLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArrowUpSLine,
  RiExpandUpDownLine,
  RiTimeLine,
  RiHeartLine,
  RiHomeLine,
  RiSearchLine,
  RiSubtractLine,
  RiAddLine,
  RiShoppingBagLine,
  RiUserLine,
  RiCloseCircleLine,
  RiCloseLine,
} from "react-icons/ri";
import {
  IoArrowBack,
  IoArrowForward,
  IoRefresh,
  IoMenu,
  IoCheckmark,
  IoCheckmarkCircleOutline,
  IoChevronDown,
  IoChevronBack,
  IoChevronForward,
  IoChevronUp,
  IoSwapVertical,
  IoTimeOutline,
  IoHeartOutline,
  IoHomeOutline,
  IoSearchOutline,
  IoRemove,
  IoAdd,
  IoCartOutline,
  IoPersonOutline,
  IoCloseCircleOutline,
  IoClose,
} from "react-icons/io5";
import {
  CgArrowLeft,
  CgArrowRight,
  CgRedo,
  CgMenu,
  CgCheck,
  CgCheckO,
  CgChevronDown,
  CgChevronLeft,
  CgChevronRight,
  CgChevronUp,
  CgSelectO,
  CgTimer,
  CgHeart,
  CgHome,
  CgSearch,
  CgMathMinus,
  CgMathPlus,
  CgShoppingBag,
  CgUser,
  CgCloseO,
  CgClose,
} from "react-icons/cg";
import {
  AiOutlineArrowLeft,
  AiOutlineArrowRight,
  AiOutlineReload,
  AiOutlineMenu,
  AiOutlineCheck,
  AiOutlineCheckCircle,
  AiOutlineDown,
  AiOutlineLeft,
  AiOutlineRight,
  AiOutlineUp,
  AiOutlineColumnHeight,
  AiOutlineClockCircle,
  AiOutlineHeart,
  AiOutlineHome,
  AiOutlineSearch,
  AiOutlineMinus,
  AiOutlinePlus,
  AiOutlineShoppingCart,
  AiOutlineUser,
  AiOutlineCloseCircle,
  AiOutlineClose,
} from "react-icons/ai";
import {
  FaArrowLeft,
  FaArrowRight,
  FaArrowRotateRight,
  FaBars,
  FaCheck,
  FaCircleCheck,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaUpDown,
  FaClock,
  FaRegHeart,
  FaHouse,
  FaMagnifyingGlass,
  FaMinus,
  FaPlus,
  FaCartShopping,
  FaRegUser,
  FaCircleXmark,
  FaXmark,
} from "react-icons/fa6";
import {
  LiaArrowLeftSolid,
  LiaArrowRightSolid,
  LiaRedoAltSolid,
  LiaBarsSolid,
  LiaCheckSolid,
  LiaCheckCircle,
  LiaChevronDownSolid,
  LiaChevronLeftSolid,
  LiaChevronRightSolid,
  LiaChevronUpSolid,
  LiaExchangeAltSolid,
  LiaClock,
  LiaHeart,
  LiaHomeSolid,
  LiaSearchSolid,
  LiaMinusSolid,
  LiaPlusSolid,
  LiaShoppingBagSolid,
  LiaUser,
  LiaTimesCircle,
  LiaTimesSolid,
} from "react-icons/lia";
import {
  TiArrowLeft,
  TiArrowRight,
  TiArrowSync,
  TiThMenu,
  TiTick,
  TiTickOutline,
  TiArrowSortedDown,
  TiChevronLeft,
  TiChevronRight,
  TiArrowSortedUp,
  TiArrowUpThick,
  TiTime,
  TiHeartOutline,
  TiHome,
  TiZoomOutline,
  TiMinus,
  TiPlus,
  TiShoppingCart,
  TiUserOutline,
  TiDeleteOutline,
  TiTimes,
} from "react-icons/ti";
import {
  TfiArrowLeft,
  TfiArrowRight,
  TfiReload,
  TfiMenu,
  TfiCheck,
  TfiCheckBox,
  TfiAngleDown,
  TfiAngleLeft,
  TfiAngleRight,
  TfiAngleUp,
  TfiArrowsVertical,
  TfiTimer,
  TfiHeart,
  TfiHome,
  TfiSearch,
  TfiMinus,
  TfiPlus,
  TfiShoppingCart,
  TfiUser,
  TfiClose,
  TfiClose as TfiX,
} from "react-icons/tfi";

export type BrandingIconLibrary =
  | "hi2"
  | "hi"
  | "lucide"
  | "md"
  | "fi"
  | "bi"
  | "bs"
  | "rx"
  | "tb"
  | "pi"
  | "ri"
  | "io5"
  | "cg"
  | "ai"
  | "fa6"
  | "lia"
  | "ti"
  | "tfi";

/** Full UI icon set formerly hardcoded to Heroicons 2. */
export type BrandUiIcons = {
  ArrowLeft: IconType;
  ArrowRight: IconType;
  ArrowPath: IconType;
  Menu: IconType;
  Check: IconType;
  CheckCircle: IconType;
  ChevronDown: IconType;
  ChevronLeft: IconType;
  ChevronRight: IconType;
  ChevronUp: IconType;
  ChevronsUpDown: IconType;
  Clock: IconType;
  Heart: IconType;
  Home: IconType;
  Search: IconType;
  Minus: IconType;
  Plus: IconType;
  Cart: IconType;
  User: IconType;
  XCircle: IconType;
  X: IconType;
};

/** Chrome subset used by header actions. */
export type ChromeIcons = Pick<
  BrandUiIcons,
  "Search" | "Heart" | "User" | "Cart"
>;

/**
 * Named imports per library — never import the whole react-icons package.
 * Default remains Heroicons 2. Social/payment icons stay on FA separately.
 */
export const BRAND_UI_ICON_MAP: Record<BrandingIconLibrary, BrandUiIcons> = {
  hi2: {
    ArrowLeft: HiOutlineArrowLeft,
    ArrowRight: HiOutlineArrowRight,
    ArrowPath: HiOutlineArrowPath,
    Menu: HiBars3,
    Check: HiOutlineCheck,
    CheckCircle: HiOutlineCheckCircle,
    ChevronDown: HiOutlineChevronDown,
    ChevronLeft: HiOutlineChevronLeft,
    ChevronRight: HiOutlineChevronRight,
    ChevronUp: HiOutlineChevronUp,
    ChevronsUpDown: HiOutlineChevronUpDown,
    Clock: HiOutlineClock,
    Heart: HiOutlineHeart,
    Home: HiOutlineHome,
    Search: HiOutlineMagnifyingGlass,
    Minus: HiOutlineMinus,
    Plus: HiOutlinePlus,
    Cart: HiOutlineShoppingBag,
    User: HiOutlineUser,
    XCircle: HiOutlineXCircle,
    X: HiOutlineXMark,
  },
  hi: {
    ArrowLeft: Hi1ArrowLeft,
    ArrowRight: Hi1ArrowRight,
    ArrowPath: Hi1ArrowPath,
    Menu: Hi1Menu,
    Check: Hi1Check,
    CheckCircle: Hi1CheckCircle,
    ChevronDown: Hi1ChevronDown,
    ChevronLeft: Hi1ChevronLeft,
    ChevronRight: Hi1ChevronRight,
    ChevronUp: Hi1ChevronUp,
    ChevronsUpDown: Hi1ChevronsUpDown,
    Clock: Hi1Clock,
    Heart: Hi1Heart,
    Home: Hi1Home,
    Search: Hi1Search,
    Minus: Hi1Minus,
    Plus: Hi1Plus,
    Cart: Hi1Cart,
    User: Hi1User,
    XCircle: Hi1XCircle,
    X: Hi1X,
  },
  lucide: {
    ArrowLeft: LuArrowLeft,
    ArrowRight: LuArrowRight,
    ArrowPath: LuRefreshCw,
    Menu: LuMenu,
    Check: LuCheck,
    CheckCircle: LuCircleCheck,
    ChevronDown: LuChevronDown,
    ChevronLeft: LuChevronLeft,
    ChevronRight: LuChevronRight,
    ChevronUp: LuChevronUp,
    ChevronsUpDown: LuChevronsUpDown,
    Clock: LuClock,
    Heart: LuHeart,
    Home: LuHouse,
    Search: LuSearch,
    Minus: LuMinus,
    Plus: LuPlus,
    Cart: LuShoppingBag,
    User: LuUser,
    XCircle: LuCircleX,
    X: LuX,
  },
  md: {
    ArrowLeft: MdArrowBack,
    ArrowRight: MdArrowForward,
    ArrowPath: MdRefresh,
    Menu: MdMenu,
    Check: MdCheck,
    CheckCircle: MdCheckCircleOutline,
    ChevronDown: MdKeyboardArrowDown,
    ChevronLeft: MdKeyboardArrowLeft,
    ChevronRight: MdKeyboardArrowRight,
    ChevronUp: MdKeyboardArrowUp,
    ChevronsUpDown: MdUnfoldMore,
    Clock: MdOutlineAccessTime,
    Heart: MdFavoriteBorder,
    Home: MdOutlineHome,
    Search: MdOutlineSearch,
    Minus: MdRemove,
    Plus: MdAdd,
    Cart: MdOutlineShoppingBag,
    User: MdOutlinePersonOutline,
    XCircle: MdOutlineCancel,
    X: MdClose,
  },
  fi: {
    ArrowLeft: FiArrowLeft,
    ArrowRight: FiArrowRight,
    ArrowPath: FiRefreshCw,
    Menu: FiMenu,
    Check: FiCheck,
    CheckCircle: FiCheckCircle,
    ChevronDown: FiChevronDown,
    ChevronLeft: FiChevronLeft,
    ChevronRight: FiChevronRight,
    ChevronUp: FiChevronUp,
    ChevronsUpDown: FiChevronsUp,
    Clock: FiClock,
    Heart: FiHeart,
    Home: FiHome,
    Search: FiSearch,
    Minus: FiMinus,
    Plus: FiPlus,
    Cart: FiShoppingBag,
    User: FiUser,
    XCircle: FiXCircle,
    X: FiX,
  },
  bi: {
    ArrowLeft: BiArrowBack,
    ArrowRight: BiRightArrowAlt,
    ArrowPath: BiRefresh,
    Menu: BiMenu,
    Check: BiCheck,
    CheckCircle: BiCheckCircle,
    ChevronDown: BiChevronDown,
    ChevronLeft: BiChevronLeft,
    ChevronRight: BiChevronRight,
    ChevronUp: BiChevronUp,
    ChevronsUpDown: BiExpandVertical,
    Clock: BiTime,
    Heart: BiHeart,
    Home: BiHome,
    Search: BiSearch,
    Minus: BiMinus,
    Plus: BiPlus,
    Cart: BiShoppingBag,
    User: BiUser,
    XCircle: BiXCircle,
    X: BiX,
  },
  bs: {
    ArrowLeft: BsArrowLeft,
    ArrowRight: BsArrowRight,
    ArrowPath: BsArrowRepeat,
    Menu: BsList,
    Check: BsCheck,
    CheckCircle: BsCheckCircle,
    ChevronDown: BsChevronDown,
    ChevronLeft: BsChevronLeft,
    ChevronRight: BsChevronRight,
    ChevronUp: BsChevronUp,
    ChevronsUpDown: BsChevronExpand,
    Clock: BsClock,
    Heart: BsHeart,
    Home: BsHouse,
    Search: BsSearch,
    Minus: BsDash,
    Plus: BsPlus,
    Cart: BsCart3,
    User: BsPerson,
    XCircle: BsXCircle,
    X: BsX,
  },
  rx: {
    ArrowLeft: RxArrowLeft,
    ArrowRight: RxArrowRight,
    ArrowPath: RxReload,
    Menu: RxHamburgerMenu,
    Check: RxCheck,
    CheckCircle: RxCheckCircled,
    ChevronDown: RxChevronDown,
    ChevronLeft: RxChevronLeft,
    ChevronRight: RxChevronRight,
    ChevronUp: RxChevronUp,
    ChevronsUpDown: RxCaretSort,
    Clock: RxClock,
    Heart: RxHeart,
    Home: RxHome,
    Search: RxMagnifyingGlass,
    Minus: RxMinus,
    Plus: RxPlus,
    Cart: RxCube,
    User: RxPerson,
    XCircle: RxCrossCircled,
    X: RxCross2,
  },
  tb: {
    ArrowLeft: TbArrowLeft,
    ArrowRight: TbArrowRight,
    ArrowPath: TbRefresh,
    Menu: TbMenu2,
    Check: TbCheck,
    CheckCircle: TbCircleCheck,
    ChevronDown: TbChevronDown,
    ChevronLeft: TbChevronLeft,
    ChevronRight: TbChevronRight,
    ChevronUp: TbChevronUp,
    ChevronsUpDown: TbSelector,
    Clock: TbClock,
    Heart: TbHeart,
    Home: TbHome,
    Search: TbSearch,
    Minus: TbMinus,
    Plus: TbPlus,
    Cart: TbShoppingBag,
    User: TbUser,
    XCircle: TbCircleX,
    X: TbX,
  },
  pi: {
    ArrowLeft: PiArrowLeft,
    ArrowRight: PiArrowRight,
    ArrowPath: PiArrowsClockwise,
    Menu: PiList,
    Check: PiCheck,
    CheckCircle: PiCheckCircle,
    ChevronDown: PiCaretDown,
    ChevronLeft: PiCaretLeft,
    ChevronRight: PiCaretRight,
    ChevronUp: PiCaretUp,
    ChevronsUpDown: PiCaretUpDown,
    Clock: PiClock,
    Heart: PiHeart,
    Home: PiHouse,
    Search: PiMagnifyingGlass,
    Minus: PiMinus,
    Plus: PiPlus,
    Cart: PiShoppingBag,
    User: PiUser,
    XCircle: PiXCircle,
    X: PiX,
  },
  ri: {
    ArrowLeft: RiArrowLeftLine,
    ArrowRight: RiArrowRightLine,
    ArrowPath: RiRefreshLine,
    Menu: RiMenuLine,
    Check: RiCheckLine,
    CheckCircle: RiCheckboxCircleLine,
    ChevronDown: RiArrowDownSLine,
    ChevronLeft: RiArrowLeftSLine,
    ChevronRight: RiArrowRightSLine,
    ChevronUp: RiArrowUpSLine,
    ChevronsUpDown: RiExpandUpDownLine,
    Clock: RiTimeLine,
    Heart: RiHeartLine,
    Home: RiHomeLine,
    Search: RiSearchLine,
    Minus: RiSubtractLine,
    Plus: RiAddLine,
    Cart: RiShoppingBagLine,
    User: RiUserLine,
    XCircle: RiCloseCircleLine,
    X: RiCloseLine,
  },
  io5: {
    ArrowLeft: IoArrowBack,
    ArrowRight: IoArrowForward,
    ArrowPath: IoRefresh,
    Menu: IoMenu,
    Check: IoCheckmark,
    CheckCircle: IoCheckmarkCircleOutline,
    ChevronDown: IoChevronDown,
    ChevronLeft: IoChevronBack,
    ChevronRight: IoChevronForward,
    ChevronUp: IoChevronUp,
    ChevronsUpDown: IoSwapVertical,
    Clock: IoTimeOutline,
    Heart: IoHeartOutline,
    Home: IoHomeOutline,
    Search: IoSearchOutline,
    Minus: IoRemove,
    Plus: IoAdd,
    Cart: IoCartOutline,
    User: IoPersonOutline,
    XCircle: IoCloseCircleOutline,
    X: IoClose,
  },
  cg: {
    ArrowLeft: CgArrowLeft,
    ArrowRight: CgArrowRight,
    ArrowPath: CgRedo,
    Menu: CgMenu,
    Check: CgCheck,
    CheckCircle: CgCheckO,
    ChevronDown: CgChevronDown,
    ChevronLeft: CgChevronLeft,
    ChevronRight: CgChevronRight,
    ChevronUp: CgChevronUp,
    ChevronsUpDown: CgSelectO,
    Clock: CgTimer,
    Heart: CgHeart,
    Home: CgHome,
    Search: CgSearch,
    Minus: CgMathMinus,
    Plus: CgMathPlus,
    Cart: CgShoppingBag,
    User: CgUser,
    XCircle: CgCloseO,
    X: CgClose,
  },
  ai: {
    ArrowLeft: AiOutlineArrowLeft,
    ArrowRight: AiOutlineArrowRight,
    ArrowPath: AiOutlineReload,
    Menu: AiOutlineMenu,
    Check: AiOutlineCheck,
    CheckCircle: AiOutlineCheckCircle,
    ChevronDown: AiOutlineDown,
    ChevronLeft: AiOutlineLeft,
    ChevronRight: AiOutlineRight,
    ChevronUp: AiOutlineUp,
    ChevronsUpDown: AiOutlineColumnHeight,
    Clock: AiOutlineClockCircle,
    Heart: AiOutlineHeart,
    Home: AiOutlineHome,
    Search: AiOutlineSearch,
    Minus: AiOutlineMinus,
    Plus: AiOutlinePlus,
    Cart: AiOutlineShoppingCart,
    User: AiOutlineUser,
    XCircle: AiOutlineCloseCircle,
    X: AiOutlineClose,
  },
  fa6: {
    ArrowLeft: FaArrowLeft,
    ArrowRight: FaArrowRight,
    ArrowPath: FaArrowRotateRight,
    Menu: FaBars,
    Check: FaCheck,
    CheckCircle: FaCircleCheck,
    ChevronDown: FaChevronDown,
    ChevronLeft: FaChevronLeft,
    ChevronRight: FaChevronRight,
    ChevronUp: FaChevronUp,
    ChevronsUpDown: FaUpDown,
    Clock: FaClock,
    Heart: FaRegHeart,
    Home: FaHouse,
    Search: FaMagnifyingGlass,
    Minus: FaMinus,
    Plus: FaPlus,
    Cart: FaCartShopping,
    User: FaRegUser,
    XCircle: FaCircleXmark,
    X: FaXmark,
  },
  lia: {
    ArrowLeft: LiaArrowLeftSolid,
    ArrowRight: LiaArrowRightSolid,
    ArrowPath: LiaRedoAltSolid,
    Menu: LiaBarsSolid,
    Check: LiaCheckSolid,
    CheckCircle: LiaCheckCircle,
    ChevronDown: LiaChevronDownSolid,
    ChevronLeft: LiaChevronLeftSolid,
    ChevronRight: LiaChevronRightSolid,
    ChevronUp: LiaChevronUpSolid,
    ChevronsUpDown: LiaExchangeAltSolid,
    Clock: LiaClock,
    Heart: LiaHeart,
    Home: LiaHomeSolid,
    Search: LiaSearchSolid,
    Minus: LiaMinusSolid,
    Plus: LiaPlusSolid,
    Cart: LiaShoppingBagSolid,
    User: LiaUser,
    XCircle: LiaTimesCircle,
    X: LiaTimesSolid,
  },
  ti: {
    ArrowLeft: TiArrowLeft,
    ArrowRight: TiArrowRight,
    ArrowPath: TiArrowSync,
    Menu: TiThMenu,
    Check: TiTick,
    CheckCircle: TiTickOutline,
    ChevronDown: TiArrowSortedDown,
    ChevronLeft: TiChevronLeft,
    ChevronRight: TiChevronRight,
    ChevronUp: TiArrowSortedUp,
    ChevronsUpDown: TiArrowUpThick,
    Clock: TiTime,
    Heart: TiHeartOutline,
    Home: TiHome,
    Search: TiZoomOutline,
    Minus: TiMinus,
    Plus: TiPlus,
    Cart: TiShoppingCart,
    User: TiUserOutline,
    XCircle: TiDeleteOutline,
    X: TiTimes,
  },
  tfi: {
    ArrowLeft: TfiArrowLeft,
    ArrowRight: TfiArrowRight,
    ArrowPath: TfiReload,
    Menu: TfiMenu,
    Check: TfiCheck,
    CheckCircle: TfiCheckBox,
    ChevronDown: TfiAngleDown,
    ChevronLeft: TfiAngleLeft,
    ChevronRight: TfiAngleRight,
    ChevronUp: TfiAngleUp,
    ChevronsUpDown: TfiArrowsVertical,
    Clock: TfiTimer,
    Heart: TfiHeart,
    Home: TfiHome,
    Search: TfiSearch,
    Minus: TfiMinus,
    Plus: TfiPlus,
    Cart: TfiShoppingCart,
    User: TfiUser,
    XCircle: TfiClose,
    X: TfiX,
  },
};

export function resolveBrandUiIcons(
  library: string | null | undefined,
): BrandUiIcons {
  if (library && library in BRAND_UI_ICON_MAP) {
    return BRAND_UI_ICON_MAP[library as BrandingIconLibrary];
  }
  return BRAND_UI_ICON_MAP.hi2;
}

export function resolveChromeIcons(
  library: string | null | undefined,
): ChromeIcons {
  const icons = resolveBrandUiIcons(library);
  return {
    Search: icons.Search,
    Heart: icons.Heart,
    User: icons.User,
    Cart: icons.Cart,
  };
}

export function isBrandingIconLibrary(
  value: string | null | undefined,
): value is BrandingIconLibrary {
  return Boolean(value && value in BRAND_UI_ICON_MAP);
}
